name: versa
type: symfony
language: php

flake:
  devshell:
    packages:
      - php82
      - php82Packages.composer

git:
  ignore:
    - /bin/

# experimental:
#   TODO: not yet supported in Symfony projects?
#   createInclusiveGitIgnoreFile: true
