#!/usr/bin/env php

<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Process\Process;

$application = new SingleCommandApplication();

$application->addArgument(
    name: 'command',
    mode: InputArgument::REQUIRED,
    description: 'The command to run',
);

$application->addOption(
    name: 'type',
    mode: InputArgument::OPTIONAL,
    description: 'The project type',
    suggestedValues: ['drupal', 'sculpin'],
);

$application->setCode(function (InputInterface $input): int {
    // TODO: only allow defined commands - build, install, test, run.
    switch ($input->getArgument('command')) {
        case 'install':
            // TODO: Composer in Docker Compose?
            $process = new Process(command: ['composer', 'install']);
            $process->setTty(true);
            $process->run();
            break;

        case 'run':
            switch ($input->getOption('type')) {
                case 'sculpin':
                    // TODO: how to pass arbitrary arguments, such as `--port 8001`?
                    $process = new Process(command: ['./vendor/bin/sculpin', 'generate', '--server', '--watch']);
                    $process->setTty(true);
                    $process->run();
                    break;
            }
            break;

        case 'test':
            // TODO: PHPUnit, Pest or ParaTest.
            // TODO: commands in Docker Compose?
            $process = new Process(command: ['./vendor/bin/phpunit']);
            $process->setTty(true);
            $process->run();
            break;
    }

    return 0;
});

$application->run();
