#!/usr/bin/env php

<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\SingleCommandApplication;

$application = new SingleCommandApplication();

$application->addOption(
    name: 'type',
    mode: InputArgument::OPTIONAL,
    description: 'The project type',
    suggestedValues: ['drupal', 'sculpin'],
);

$application->setCode(function (InputInterface $input): int {
    dd(
        $input->getOption('type'),
    );

    return 0;
});

$application->run();
